name: Hello World

on:
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, World"

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Print out the operating system of runner
        run: echo "Running on ${{ runner.os }}"

      - name: Print out the date and time
        run: echo "Current date and time is ${{ github.event.inputs.date_time }}"

      - name: Iterate from 0 to 100
        run: |
          for i in $(seq 0 100); do
            echo "Current number is $i"
          done